// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

// ヘッダのドロップダウン
import DropdownController from './dropdown_controller'
application.register('dropdown', DropdownController)

// アラームストップ時のモーダル表示用
import ModalController from "./modal_controller"
application.register("modal", ModalController)

// 検索機能用
import SearchController from "./search_controller"
application.register("search", SearchController)

// クリップボードにコピー用
import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

// プッシュ通知の購読処理用
import PushNotificationController from "./push_notification_controller"
application.register("push-notification", PushNotificationController)

// PWAホーム画面追加の案内モーダル用
import PwaInstallController from "./pwa_install_controller"
application.register("pwa-install", PwaInstallController)

// ダークモード・ライトモードの切り替えボタン用
import ThemeController from "./theme_controller"
application.register("theme", ThemeController)